### ISSUE TITLE
UseCases/Telco_4d_Analytics/

### ISSUE THREAD

**Issue by mrconway** [Teradata/jupyter-demos#203]
Customer Journey Visualizations

**Comment by mrconway** [comment]
Compare different customer journeys across a group of cohorts. It would be cool to track these journeys over time.

**Comment by nupur-lal** [comment]
Updating according to the changes suggested at 
https://teradata.sharepoint.com/:w:/t/PortfolioMarketingTeam/EQssx6g342JOpj--QBkTY48B_aFtirVF6OuS3jTtNkUuEA?e=ywclLC
