### ISSUE TITLE
Add OpenAI UDF functions to call OpenAI embeddings for product recommendations during product search

### ISSUE THREAD

**Issue by chetan-hirapara** [Teradata/jupyter-demos#395]
Add UDF functions to call OpenAI

**Here a documentation for UDF:**

https://teradata-pe.atlassian.net/wiki/spaces/ALL/pages/32507260/Runbook+for+API+Request+UDF

**Comment by DallasBowden** [comment]
Need to verify with Pranay.

**Comment by chetan-hirapara** [comment]
This task is done. It is for TDApiClient for OpenAI embeddings
