### ISSUE TITLE
Enhance financial chatbot - External data integrations with chatbot

### ISSUE THREAD

**Issue by chetan-hirapara** [Teradata/jupyter-demos#456]
Based on Industry Analytics request, can you please extend it to
-	Include Q&A related to finding the location
-	Include Q&A related for additional house moving services

PPT: https://teradata.sharepoint.com/:p:/t/PortfolioMarketingTeam/EVukgdvCUEpOuuNFTj5vpVcBSHOMlkWzDDnqVv-LXT6F3Q?e=aYcRds&CID=A7E5AD23-184E-4293-A38C-C30B1469FB3A&wdLOR=c8F962F18-B426-4F1E-B8BF-767841BBD1B1

external data: https://www.microburbs.com.au/Vic/Melbourne/Melbourne-Inner-City/Melbourne

**Comment by DallasBowden** [comment]
Waiting for input from Pranay.
